# Generated by Django 3.2.7 on 2021-09-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('task', models.TextField(verbose_name='описание')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
