# Generated by Django 3.2.7 on 2022-01-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsites', '0002_auto_20210908_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
    ]
