# Generated by Django 3.2.7 on 2022-01-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsites', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
